### ISSUE TITLE
Reasons behind the fork

### ISSUE THREAD

**Issue by drybjed** [ganto/ansible-debops-secret#2]
Hi @ganto! I noticed that you are forking DebOps roles, apparently taken out from the monorepo. I'm curious about the reasons behind that move. Could you spill the beans, either here or in private? Thanks in advance. :-)

**Comment by ganto** [comment]
I just needed a quick way to use the roles in their latest version via `ansible-galaxy`. 

Actually I didn't really dig into this collection thing yet, but from what I understood, it's not really there yet, that you could use DebOps roles like it used to be back in the days with the split repositories.

**Comment by drybjed** [comment]
I see, that explains it.

Yes, DebOps as an Ansible Collection isn't really usable, due to [issues with role dependencies](https://github.com/ansible/galaxy/issues/1938). Since the proposed solution of using `import_role` task instead of specifying the dependencies directly seems to work, I plan to convert all roles to this solution before the `v2.0.0` release. Although there still might be some issues with role naming - DebOps might be forced to drop the `debops.` prefix from roles at some point so that will be interesting.

For now, you should still be able to just point to the DebOps monorepo using `galaxy.yml` file and clone them wherever, add the `ansible/roles/` directory in the `roles_path` parameter in `ansible.cfg` file and make DebOps roles work that way.
